#!/usr/bin/env php
<?php

require_once __DIR__.'/PluzKernel.php';

use Symfony\Framework\FoundationBundle\Console\Application;

$kernel = new PluzKernel('dev', true);

$application = new Application($kernel);
$application->run();
