imports:
    - { resource: config.yml }

web.config:
    toolbar: true

zend.logger:
    priority: info
    path:     %kernel.root_dir%/logs/%kernel.environment%.log

doctrine.dbal:
  connections:
    default:
      driver:               PDOMySql
      dbname:               symfony2blog
      user:                 root
      password:             mysql
      host:                 localhost
      port:                 ~
