parameters:
    kernel.include_core_classes: false

kernel.config: ~
web.config: ~
web.templating: ~

doctrine.orm:
  default_entity_manager:   default
  entity_managers:
    default:
      connection:           default